### ISSUE TITLE
[PROPOSAL] Specify format on import

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#112]
# Problem

We need to pseudonymize a files table, by generating a new content (column data) based on the value of the `name` column.

We use this table.yaml file (note the `data` column is not selected because we don't need it as it is replaced by new value).

```yaml
  - name: files
    keys:
      - id
    columns:
      - name: id
      - name: name
```

The column `data` is added and generated by PIMO.

On the push, there is a problem because the value of `data` is in base64 in the JSON stream, so we need to update the table.yaml file 

```yaml
  - name: files
    keys:
      - id
    columns:
      - name: id
      - name: name
      - name: data
        export: binary
```

Now the push is OK, the data values are treated as base64. But the pull will now extract the column data from the source database. This is a concern about performance, because this extraction is costly and useless.

# Solution (edited 2022-08-02)

Currently the `import` property can only impact the in-memory data type (int, float, string, ...). But this property could (should?) also enable the possibility to impact how the data is read from the JSON stream.

A way to do this without breaking compatibility is to continue the support of `import: []byte`, `import: string`, etc... and add the support of `import: binary`, `import: datetime`, etc... (same options as `export` properties). To set the data type **and** the format at the same time, this king of value can be used for the `import` property : `import: binary(int64)` (i.e. : `import: format(type)`).

So our example become :

```yaml
  - name: files
    keys:
      - id
    columns:
      - name: id
      - name: name
      - name: data
        import: binary
```
