### ISSUE TITLE
[PROPOSAL] Import file

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#237]
**table.yaml**

```yaml
  - name: attachments
    keys:
      - id
    columns:
      - name: content
        import: file
```

LINO will interpret the input value as a path to a file, and will use the content of the file as data.
