### ISSUE TITLE
[BUG?] Pull behavior changed from v1.10.0 on

### ISSUE THREAD

**Issue by CapKicklee** [CGI-FR/LINO#245]
### Context

Until LINO v1.9.2 included, when pulling a table with a child relationship, data from child were pulled as a JSON Object :

```yml
{
    "myField1": {
        "childField1": "",
        "childField2": "2021-07-06T09:59:13+02:00",
        "childField3": "2021-07-13T12:04:19+02:00",
        ...
    },
    "myField2": "bla",
    "myField3": "9921196128284",
    ...
}
```

Starting from v1.10.0, same data are pulled as a JSON Array containing a single JSON Object :

```yml
{
    "myField1": [
        {
            "childField1": "",
            "childField2": "2021-07-06T09:59:13+02:00",
            "childField3": "2021-07-13T12:04:19+02:00",
            ...
        }
    ]
    "myField2": "bla",
    "myField3": "9921196128284",
    ...
}
```

### Asking

Is it a desired behavior? If so, is there any way to get the previous one without going back to v1.9.2?

Could this also be documented so that it becomes a known kind of breaking change?

Thanks

**Comment by youen** [comment]
Since the integration test of version v1.9.2 describes LINO's current behavior, I feel like saying that we fixed a bug in version v1.10.0 ¯_(ツ)_/¯

```yaml

- name: pull child
  steps:
    - script: sed -i "s/true/false/g" ingress-descriptor.yaml
    - script: lino id set-child-lookup staff_store_id_fkey true
    - script: lino pull source --limit 1
      assertions:
        - result.code ShouldEqual 0
        - result.systemout ShouldEqual {"address_id":1,"last_update":"2006-02-15T09:57:12Z","manager_staff_id":1,"staff_store_id_fkey":[{"active":true,"address_id":3,"email":"Mike.Hillyer@sakilastaff.com","first_name":"Mike","last_name":"Hillyer","last_update":"2006-05-16T16:13:11.79328Z","password":"8cb2237d0679ca88db6464eac60da96345513964","picture":"iVBORw0KWgo=","staff_id":1,"store_id":1,"username":"Mike"}],"store_id":1}
        - result.systemerr ShouldBeEmpty
    - script: lino id set-child-lookup staff_store_id_fkey false
```

https://github.com/CGI-FR/LINO/blob/26987ac443c2ec9ae33d9ba7279627d63c2e1ddd/tests/suites/pull/single_relation.yml#L36
