### ISSUE TITLE
[PROPOSAL] Improve `lino table extract` to Automatically Initialize Column Information Based on Database Schema

### ISSUE THREAD

**Issue by youen** [CGI-FR/LINO#254]
**Description:**
Currently, users have reported anomalies when using the LINO tool, particularly regarding the automatic detection of column types during data extraction. When extracting data from databases such as PostgreSQL, numeric columns are not recognized correctly, leading to incorrect representations of numeric values in the output JSON format (#244).

**Problem:**
Numeric columns are not displaying correct numeric values in the output JSON format. For instance, a value like `"rating": "TkMtMTc="` is incorrect.

**Expected Outcome:**
The LINO tool should consider the column data type during extraction to ensure that numeric values are displayed correctly in the output JSON format.

**Additional Information:**
- A current workaround involves manually updating the `tables.yaml` file to include column information, specifying `export: numeric` for numeric columns. However, this approach is cumbersome, especially for large databases.
- It is crucial to address this issue to enhance the usability and accuracy of the LINO tool, particularly for users dealing with numeric data.

**Proposed Solution:**
Enhance the `lino table extract` command to automatically initialize column information, including data types, based on the database schema. This improvement would streamline the data extraction process and ensure accurate representation of numeric values in the output JSON format.

**Suggested Implementation Steps:**
1. Modify the `lino table extract` command to analyze the database schema and retrieve column information.
2. Determine the data type of each column (e.g., numeric, string, date) based on the database schema.
3. Automatically populate the `tables.yaml` file with column information, including the appropriate data type for each column.
4. Ensure backward compatibility and error handling for databases with complex schemas or unusual column types.

**Benefits:**
- Simplifies the data extraction process for users by eliminating the need for manual configuration of column information.
- Improves the accuracy of data representation in the output JSON format, particularly for numeric values.
- Enhances the overall usability and efficiency of the LINO tool, making it more accessible to a wider range of users.

**Related Issue:**
This enhancement request is related to issue #244 , which addresses similar challenges in data extraction and representation.

**Comment by adrienaury** [comment]
> Automatically populate the tables.yaml file with column information, including the appropriate data type for each column.

This step should include following information:
- database datatype
- adequate JSON type to represent the data (currently covered by the `export` field)
- size (for string : maximum length, for numeric types : bit size)

**Comment by Chao-Ma5566** [comment]
For incorporating database data type and column size, a `dbinfo `field can be added for each column with four possible under categories: `dbtype`, `size`, `precision`, and `length`.

- Each column will include a `dbtype`, except for those where the type cannot be detected, which will be logged as a warning.
- `Length`, `size`, and `precision `will only be added for columns with that information available.

Here is an exemple: 

```yml
- name: film
    keys:
      - film_id
    columns:
      - name: film_id
        dbinfo:
          - dbtype: INT4
      - name: title
        export: string
        dbinfo:
          - dbtype: VARCHAR
          - length: 255
      - name: description
        export: string
        dbinfo:
          - dbtype: TEXT
          - length: 9223372036854775807
      - name: release_year
        dbinfo:
          - dbtype: INT4
      - name: rental_rate
        export: numeric
        dbinfo:
          - dbtype: NUMERIC
          - size: 2
          - precision: 4
      - name: replacement_cost
        export: numeric
        dbinfo:
          - dbtype: NUMERIC
          - size: 2
          - precision: 5
```

Similar to how we introduced the `--only-tables` flag for the `lino table extract` command to preserve the previous behavior, another flag `--all` can be added to include this information in `table.yaml`. By default, only the column names and export type will be present for columns requiring transformation.

**Comment by adrienaury** [comment]
There is some unnecessary arrays in your example, fix :

```yaml
- name: film
    keys:
      - film_id
    columns:
      - name: film_id
        dbinfo:
          dbtype: INT4
      - name: title
        export: string
        dbinfo:
          dbtype: VARCHAR
          length: 255
      - name: description
        export: string
        dbinfo:
          dbtype: TEXT
          length: 9223372036854775807
      - name: release_year
        dbinfo:
          dbtype: INT4
      - name: rental_rate
        export: numeric
        dbinfo:
          dbtype: NUMERIC
          size: 2
          precision: 4
      - name: replacement_cost
        export: numeric
        dbinfo:
          dbtype: NUMERIC
          size: 2
          precision: 5
```
