### ISSUE TITLE
feat: import no

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#324]
## Use case

As a LINO user, I want to export primary keys with the pull command, but I don't want the push command to update the primary key (just use it for update clause).

### Solution

Tag column as `import: no` in the tables.yaml file :

```yaml
version: v1
tables:
  - name: "TABLE"
    keys:
      - "ID1"
      - "ID2"
    columns:
      - name: "ID1"
        import: "no"
      - name: "ID2"
        import: "no"
```
