### ISSUE TITLE
[PROPOSAL] Exported columns definition

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#33]
# Objective

A new section `columns` under tables elements inside tables.yaml file lists exported columns in the JSON output.

Example :

```yaml
version: v1
tables:
  - name: public.actor
    keys:
      - actor_id
    columns:
      - name: "first_name"
      - name: "last_name"
```

## Default behavior

If not present, LINO outputs all columns in alphabetical order, this is the current behavior and to not break compatibility with existing configurations

## Order

If at least a column is defined inside the `columns` section, then LINO will output only the defined column(s) and in the order they appear in the file.

## Primary keys

Primary keys are necessary for the push action, so, even if not present in the `columns`section, they will always be exported in the output.

## Foreign keys

Foreign keys involved in active relations must be exported even if not present in the `columns`section.

## Type

The `name` property is mandatory. The `type` property is optional and ask LINO to convert the column values to a certain JSON type in the output.

Example :

```yaml
version: v1
tables:
  - name: public.actor
    keys:
      - actor_id
    columns:
      - name: "first_name"
        type: string
      - name: "last_name"
        type: string
```

Available types are:
 - string : LINO output the value as a string in the JSON, e.g. : `"hello"`.
 - decimal : LINO output the value as a decimal number in the JSON, e.g. : `25.2`.
 - integer : LINO output the value as an integer in the JSON, e.g. : `25`.
 - boolean : LINO output the value as a boolean in the JSON, e.g. : `true`.
 - base64 : LINO output the value base64 encoded in the JSON, e.g. : `aGVsbG8=`.

**Comment by youen** [comment]
Not all use case have to export primary keys or foreign keys. Primary keys and foreign keys are implicitly exported as nested json object. Other use have to export all columns in the table.

We can add an option to specify the pull behavior.
- all : export all columns and respect listed columns
- with-keys : export listed columns and pk + fk
- only : export only listed  columns

Example :

```yaml
version: v1
tables:
  - name: public.actor
    keys:
      - actor_id
    columns:
      - name: "first_name"
        type: string
      - name: "last_name"
        type: string
   export: all
```

**Comment by adrienaury** [comment]
Then default behavior should be `export: all`

**Comment by youen** [comment]
# Impacts in the code for this US :

## pull

- Create new interface Column in model
- Add new attribut in `Table` interface
https://github.com/CGI-FR/LINO/blob/4a3080889c13e3f329b253faa4ba5aec07efcdf7/pkg/pull/model.go#L28-L32

- Use columns definition to dynamically change `select` statement from `*` to columns names.
https://github.com/CGI-FR/LINO/blob/4a3080889c13e3f329b253faa4ba5aec07efcdf7/internal/infra/pull/sql_datasource.go#L80

**Comment by adrienaury** [comment]
PR #38 will take care of these 2 points

- Create new interface Column in model
- Add new attribut in Table interface

**Comment by adrienaury** [comment]
To manage a proper push of a jsonline after data tyoes has been modified, here is a proposition to make a reverse conversion before pushing 

```yaml
version: v1
tables:
  - name: film
    keys:
      - film_id
    columns:
      - name: "film_id"
        export: string
        import: integer
```
