### ISSUE TITLE
feat: separate structure and profile in tables.yaml

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#337]
## Problem

`tables.yaml` file mixes 2 types of informations
1. information about the datasource structure (tables names, primary keys, dbinfos types)
2. information about extract or load operations (list of columns, export format, import format)

This example :

```yaml
version: "1"
tables:
- name: "film"
    keys: ["film_id"]
    columns:
      - name: "film_id"
        dbinfo:
          type: "bigserial"
      - name: "title"
        dbinfo:
          type: "varchar"
          length: 30
          bytes: true
      - name: "picture"
        export: "presence"
        import: "file"
        dbinfo:
          type: "BLOB"
```

Contains information about the datasource structure (tables names, primary keys, dbinfos types) :

```yaml
version: "1"
tables:
- name: "film"
    keys: ["film_id"]
    columns:
      - name: "film_id"
        dbinfo:
          type: "bigserial"
      - name: "title"
        dbinfo:
          type: "varchar"
          length: 30
          bytes: true
      - name: "picture"
        dbinfo:
          type: "BLOB"
```

And information about extract or load operations (list of columns to export, export formats, import formats) :

```yaml
version: "1"
tables:
- name: "film"
    columns:
      - name: "film_id"
      - name: "title"
      - name: "picture"
        export: "presence"
        import: "file"
```

There is a difference between each type of information
1. information about the datasource structure never change
2. information about extract or load operations will vary depending on the use case

Therefore, it would be interresting to separate these concerns in different files.

## Solution
