### ISSUE TITLE
Incorrect behavior of lino relation extract command with composite primary key on Oracle

### ISSUE THREAD

**Issue by youen** [CGI-FR/LINO#341]
**Description:**
When using the `lino relation extract` command with Lino versions 2.5.0 and 3.0.2 on an Oracle database, the command generates two separate relations instead of a single relation with a composite key. Here is an illustrative example:

**Generated YAML:**
```yaml
- name: FKDD01421_DD01405
  parent:
    name: DD01405_COMPETENCE
    keys:
      - ID_INDIVIDU
  child:
    name: DD01421_COMPETENCE_VALIDEE
    keys:
      - ID_INDIVIDU
- name: FKDD01421_DD01405
  parent:
    name: DD01405_COMPETENCE
    keys:
      - ID_COMPETENCE
  child:
    name: DD01421_COMPETENCE_VALIDEE
    keys:
      - ID_COMPETENCE
```

**Expected YAML:**
The command should generate a single relation with a composite key as shown below:
```yaml
- name: FKDD01421_DD01405
  parent:
    name: DD01405_COMPETENCE
    keys:
      - ID_COMPETENCE
      - ID_INDIVIDU
  child:
    name: DD01421_COMPETENCE_VALIDEE
    keys:
      - ID_INDIVIDU
      - ID_COMPETENCE
```

**Affected Versions:**
- Lino 2.5.0
- Lino 3.0.2

**Environment:**
- DBMS: ORACLE
