### ISSUE TITLE
Feature Request: Adding "Preserve Null" Functionality in LINO Push update

### ISSUE THREAD

**Issue by youen** [CGI-FR/LINO#361]
Hello,

I would like to suggest the addition of a feature for managing columns in the table configuration of LINO. This feature would be a "preserve null" option which allows updating a column only if its current value in the database is different from null. This option would be very useful for cases where we want to retain an existing null value during push update operations.
## Example:

Suppose we have a table actor in the demo database  with columns actor_id, first_name, last_name, and last_update. When we configure the last_update column with preserve null, LINO should proceed as follows during a push update operation:

### Initial state of the table:

| actor_id | first_name | last_name | last_update        |
|----------|------------|-----------|--------------------|
| 1        | Tom        | Hanks     | 2025-01-01 10:00:00|
| 2        | Meryl      | Streep    | NULL               |
| 3        | Will       | Smith     | 2025-01-01 12:00:00|

### Data to push:
```jsonl
{"actor_id":1,"first_name":"Jerry","last_name":"Seinfeld","last_update":"2025-03-21 10:00:00"}
{"actor_id":2,"first_name":"Julia","last_name":"Roberts","last_update":"2025-03-21 11:00:00"}
{"actor_id":3,"first_name":"Chris","last_name":"Rock","last_update":"2025-03-21 12:00:00"}
```

### Expected result with preserve null:

| actor_id | first_name | last_name | last_update        |
|----------|------------|-----------|--------------------|
| 1        | Jerry      | Seinfeld  | 2025-03-21 10:00:00|
| 2        | Julia      | Roberts   | NULL               |
| 3        | Chris      | Rock      | 2025-03-21 12:00:00|

## Proposed configuration for table.yml:
```yaml
version: v1
tables:
  - name: actor
    keys:
      - actor_id
    columns:
      - name: actor_id
        dbinfo:
          type: INT4
      - name: first_name
        export: string
        dbinfo:
          type: VARCHAR
          length: 45
          bytes: true
      - name: last_update
        export: timestamp
        dbinfo:
          type: TIMESTAMP
          preserve: "null"  # empty or blank like pimo preserve configuration 
```

Thank you for considering this request.
