### ISSUE TITLE
[PROPOSAL] Export columns options

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/LINO#95]
Not all use case have to export primary keys or foreign keys. Primary keys and foreign keys are implicitly exported as nested json object. Other use have to export all columns in the table.

We can add an option to specify the pull behavior.
- all : export all columns and respect listed columns
- with-keys : export listed columns and pk + fk
- only : export only listed  columns

Example :

```yaml
version: v1
tables:
  - name: public.actor
    keys:
      - actor_id
    columns:
      - name: "first_name"
        type: string
      - name: "last_name"
        type: string
    export: all
```

_Originally posted by @youen in https://github.com/CGI-FR/LINO/issues/33#issuecomment-875717615_
